{{ $_ := set . "appName" "mgmt-sa" }}

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "metadata.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
