{{ $_ := set . "appName" "mgmt-clusterrolebinding" }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "metadata.name" . }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mgmt-clusterrole
subjects:
  - kind: ServiceAccount
    name: mgmt-sa
    namespace: {{ .Values.namespace }}
  