{{ $_ := set . "appName" "notary-db-svc" }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
spec:
  selector:
{{- include "metadata.selectorLabels" . | indent 4 }}
  type: ClusterIP
  ports:
  - name: tcp-notary-db
    protocol: TCP
    port: 3306
    targetPort: 3306
