{{ $_ := set . "appName" "notary-signer-certs" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metadata.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
type: Opaque
data:
  notary-signer.crt: {{ .Files.Get "certs/notary-signer.crt" | b64enc }}
  notary-signer.key: {{ .Files.Get "certs/notary-signer.key" | b64enc }}
  notary-server.crt: {{ .Files.Get "certs/notary-server.crt" | b64enc }}
