{{ $_ := set . "appName" "notary-signer-cm" }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metadata.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
data:
  config: |
    {
      "server": {
        "grpc_addr": ":7899",
        "tls_cert_file": "./certs/notary-signer.crt",
        "tls_key_file": "./certs/notary-signer.key",
        "client_ca_file": "./certs/notary-server.crt"
      },
      "logging": {
        "level": "debug"
      },
      "storage": {
        "backend": "mysql",
        "db_url": "{{ template "metadata.database.signer.cm.url" . }}",
        "default_alias": "{{ .Values.signer.cm.passwordalias1Name }}"
      }
    }
