{{ $_ := set . "appName" "notary-server-svc" }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
spec:
  selector:
{{- include "metadata.selectorLabels" . | indent 4 }}
  type: {{ .Values.server.svc.type }}
  ports:
  - name: https-server
    protocol: TCP
    targetPort: 4443
    port: {{ .Values.server.svc.port }}
