{{ $_ := set . "appName" "notary-server-cm" }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metadata.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
data:
  config: |
    {
      "server": {
        "http_addr": ":4443",
        "tls_key_file": "./certs/notary-server.key",
        "tls_cert_file": "./certs/notary-server.crt"
      },
      "trust_service": {
        "type": "remote",
        "hostname": "notary-signer-svc",
        "port": "7899",
        "key_algorithm": "ecdsa",
        "tls_ca_file": "./certs/root-ca.crt",
        "tls_client_cert": "./certs/notary-server.crt",
        "tls_client_key": "./certs/notary-server.key"
      },
      "logging": {
        "level": "debug"
      },
      "storage": {
        "backend": "mysql",
        "db_url": "{{ template "metadata.database.server.cm.url" . }}"
      }
    }
