{{ $_ := set . "appName" "notary-server-certs" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metadata.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "metadata.labels" . | indent 4 }}
type: Opaque
data:
  root-ca.crt: {{ .Files.Get "certs/root-ca.crt" | b64enc }}
  notary-server.crt: {{ .Files.Get "certs/notary-server.crt" | b64enc }}
  notary-server.key: {{ .Files.Get "certs/notary-server.key" | b64enc }}
